"""
Generates a GitHub PR review comment from hc-maestro findings.
"""
from catalog import get_threat_by_id

_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "informational": "⚪",
}

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "informational"]

_ATTRIBUTION = (
    "\n<sub>Generated by "
    "[hc-maestro](https://github.com/thehipsterciso/hc-maestro-action) v0.1.0 — "
    "MAESTRO-as-Code by Thomas Jones (thehipsterciso). "
    "Spec: [CC BY 4.0](https://github.com/thehipsterciso/hc-maestro-spec)</sub>"
)


def findings_to_comment(findings, catalog, pr_desc=""):
    """Return a markdown string for a GitHub PR review comment."""
    if not findings:
        return "### hc-maestro Threat Analysis\n\n✅ No MAESTRO threats detected." + _ATTRIBUTION

    sorted_findings = sorted(
        findings,
        key=lambda f: _SEVERITY_ORDER.index(f.get("severity", "informational"))
    )

    by_severity = {}
    for f in sorted_findings:
        sev = f.get("severity", "medium")
        by_severity.setdefault(sev, []).append(f)

    lines = ["### hc-maestro MAESTRO Threat Analysis", ""]

    summary_rows = []
    for sev in _SEVERITY_ORDER:
        count = len(by_severity.get(sev, []))
        if count:
            emoji = _SEVERITY_EMOJI.get(sev, "")
            summary_rows.append(f"| {emoji} {sev.capitalize()} | {count} |")

    if summary_rows:
        lines += ["| Severity | Count |", "|----------|-------|"] + summary_rows + [""]

    lines.append("---")
    lines.append("")

    for f in sorted_findings:
        tid = f["threat_id"]
        severity = f.get("severity", "medium")
        emoji = _SEVERITY_EMOJI.get(severity, "")
        threat = get_threat_by_id(catalog, tid)

        lines.append(f"#### {emoji} `{tid}` — {f.get('title', 'Finding')}")
        lines.append("")

        location_parts = []
        if f.get("file"):
            loc = f"**`{f['file']}`**"
            if f.get("line"):
                loc += f":{f['line']}"
            location_parts.append(loc)
        if location_parts:
            lines.append(f"**Location:** {', '.join(location_parts)}")
            lines.append("")

        if f.get("description"):
            lines.append(f.get("description"))
            lines.append("")

        if f.get("evidence"):
            lines.append("**Evidence:**")
            lines.append("```")
            lines.append(f.get("evidence").strip())
            lines.append("```")
            lines.append("")

        if f.get("recommendation"):
            lines.append(f"**Recommendation:** {f.get('recommendation')}")
            lines.append("")

        if threat:
            mitigations = threat.get("mitigations", [])
            if mitigations:
                lines.append("**MAESTRO Mitigations:**")
                for m in mitigations[:3]:
                    lines.append(f"- {m}")
                lines.append("")

            refs = threat.get("references", [])
            if refs:
                ref_links = ", ".join(f"[{r['title']}]({r['url']})" for r in refs[:2])
                lines.append(f"**References:** {ref_links}")
                lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(_ATTRIBUTION)
    return "\n".join(lines)
